<?php

namespace AppBundle\Repository;

/**
 * MediaIpsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaIpsRepository extends \Doctrine\ORM\EntityRepository
{
}
