<?php

namespace AppBundle\Repository;

/**
 * RoutingRequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoutingRequestsRepository extends \Doctrine\ORM\EntityRepository
{
}
