<?php

namespace AppBundle\Repository;

/**
 * RoutingRegistersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoutingRegistersRepository extends \Doctrine\ORM\EntityRepository
{
}
