<?php

namespace AppBundle\Repository;

/**
 * SipListenersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SipListenersRepository extends \Doctrine\ORM\EntityRepository
{
}
