#!/usr/bin/perl

use v5.10;
use strict;
use Term::ANSIColor qw(:constants);
no warnings;

# Enable hot-piping
$|=1;

my $hostname=`hostname`;
chomp $hostname;

while (<>) {
    # Avoid hostname from logged message
    s#$hostname ##;

    # Avoid binary(pid) from logged message
    s#^(.*)\s+\S+opensips\[\d+\]:\s+(.*)#[$1] $2#;

    # When printing $mb, opensips logs this characters instead of \n
    s!#015!!g;
    s!#012!\n!g;

    # If '[<null>]', remove
    s!\[<null>\] !!g;

    # Print each message with its colour
    given ($_) {
        when (/(.*) ALERT:\s*(.*)/) { say RED "$1 $2"; }
        when (/(.*) BUG:\s*(.*)/) { say RED "$1 $2"; }
        when (/(.*) CRITICAL:\s*(.*)/) { say RED "$1 $2"; }
        when (/(.*) ERROR:\s*(.*)/) { say RED "$1 $2"; }
        when (/(.*) WARNING:\s*(.*)/) { say YELLOW "$1 $2"; }
        when (/(.*) NOTICE:\s*(.*)/) { say MAGENTA "$1 $2"; }
        when (/(.*) INFO:\s*(.*)/) { say GREEN "$1 $2"; }
        when (/(.*) DEBUG:\s*(.*)/) { say CYAN "$1 $2"; }
        default { print WHITE $_; }
    }
}

